<?php

namespace CleanPhp\TrackerBundle\Entity;

use CleanPhp\Domain\Label;
use CleanPhp\Model\LabelRepositoryInterface;
use Doctrine\ORM\EntityRepository;

/**
 * LabelEntityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LabelEntityRepository extends EntityRepository implements LabelRepositoryInterface
{
    public function save(Label $label)
    {
        $this->_em->persist($label);
        $this->_em->flush();
    }
}
