<?php

namespace CleanPhp\TrackerBundle\Entity;

use CleanPhp\Model\MoneyRepositoryInterface;
use Doctrine\ORM\EntityRepository;

/**
 * MoneyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MoneyRepository extends EntityRepository implements MoneyRepositoryInterface
{
    public function save(\CleanPhp\Domain\Money $money)
    {
        $this->_em->persist($money);
        $this->_em->flush();
    }
}
