<?php

namespace CleanPhp\TrackerBundle\Entity;

use CleanPhp\Model\TagRepositoryInterface;
use Doctrine\ORM\EntityRepository;

/**
 * TagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagRepository extends EntityRepository implements TagRepositoryInterface
{
    public function save(\CleanPhp\Domain\Tag $tag)
    {
        $this->_em->persist($tag);
        $this->_em->flush();
    }
}
