CleanPhp\TrackerBundle\Entity\Tag:
    type: entity
    table: null
    repositoryClass: CleanPhp\TrackerBundle\Entity\TagRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255

    lifecycleCallbacks: {  }
