services:
    tracker.tag_repository:
        class: CleanPhp\TrackerBundle\Entity\TagRepository
        factory_service: doctrine.orm.entity_manager
        factory_method:  getRepository
        arguments:
            - CleanPhpTrackerBundle:Tag

    tracker.validator_adapter:
        class: CleanPhp\TrackerBundle\Validator\ValidatorAdapter
        arguments:
            - @validator

    tracker.create_tag:
        class: CleanPhp\Model\CreateTag
        arguments:
            - @tracker.tag_repository
            - @tracker.validator_adapter
